In [1]:
import numpy as np

## Datatype & Attributes

In [11]:
#Numpy's main datatype is ndarry
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [12]:
type(a1)

numpy.ndarray

In [13]:
a2 = np.array([[2,35,5],[2,35,5]])

In [14]:
a2

array([[ 2, 35,  5],
       [ 2, 35,  5]])

In [16]:
a3 = np.array([[[1,34,4] ,[1,5,2],[135,252,25]]])

In [17]:
a3

array([[[  1,  34,   4],
        [  1,   5,   2],
        [135, 252,  25]]])

In [19]:
a3.shape

(1, 3, 3)

In [20]:
a1.shape

(3,)

In [21]:
a2.shape

(2, 3)

In [22]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [23]:
a1.dtype

dtype('int64')

In [24]:
sample_array = np.array([1,2,4])

In [27]:
ones = np.ones((2,4) )

In [28]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
ones.shape

(2, 4)

In [30]:
zero= np.zeros((1,2))

In [31]:
zero

array([[0., 0.]])

In [57]:
random_array = np.random.randint(15,size= (5,3))

In [48]:
random_array

array([[8, 8, 7],
       [5, 2, 8],
       [3, 6, 8],
       [1, 2, 4],
       [6, 6, 3]])

In [53]:
a = np.array([1,2,3])

In [54]:
b = np.array([2,4])

## Viewing Arrays and Matrices

In [58]:
np.unique(random_array)

array([ 0,  3,  4,  5,  6,  7,  9, 10, 12, 13])

In [60]:
random_array


array([[13,  7, 10],
       [ 3,  6,  5],
       [ 4,  0, 13],
       [ 9,  0, 13],
       [12,  0,  7]])

In [73]:
random_array[1,1] =1

In [74]:
random_array

array([[13,  7, 10],
       [ 3,  1,  5],
       [ 4,  0, 13],
       [ 9,  0, 13],
       [12,  0,  7]])

In [63]:
random_array.ndim

2

In [66]:
random_array

array([[13,  7, 10],
       [ 3,  6,  5],
       [ 4,  0, 13],
       [ 9,  0, 13],
       [12,  0,  7]])

In [70]:
random_array[:0,1]

array([], dtype=int64)

In [71]:
a = np.random.randint(10,size = (2,3,4,5))

In [76]:
lis = [1,3]

In [77]:
np.sum(lis)

4

In [82]:
massive_arary = np.random.random(100000)

In [84]:
massive_arary[0:100]

array([0.10286045, 0.61715457, 0.49204053, 0.65479477, 0.7170176 ,
       0.56839213, 0.48197566, 0.02346045, 0.86695836, 0.84005103,
       0.85778794, 0.438246  , 0.3400617 , 0.93569391, 0.99196927,
       0.46785622, 0.33648593, 0.48711067, 0.77426756, 0.51429292,
       0.9402834 , 0.61780975, 0.48726951, 0.00346412, 0.9019331 ,
       0.93930213, 0.3006964 , 0.08162486, 0.4281501 , 0.5241268 ,
       0.80790706, 0.34577103, 0.62040731, 0.08532284, 0.57579424,
       0.58139193, 0.18797756, 0.42486628, 0.88832758, 0.25445275,
       0.2977975 , 0.27167925, 0.93460494, 0.85529712, 0.89798185,
       0.50325973, 0.23631828, 0.33276868, 0.90257288, 0.47404549,
       0.3016481 , 0.28901064, 0.75986884, 0.37312633, 0.47951128,
       0.09870058, 0.28882736, 0.55342597, 0.80752591, 0.39602406,
       0.73957954, 0.56541873, 0.98986039, 0.95225415, 0.28296318,
       0.68796452, 0.36235123, 0.99030808, 0.8806946 , 0.06046002,
       0.97028735, 0.4971657 , 0.99540808, 0.012275  , 0.68586

In [91]:
%timeit sum(massive_arary) 
%timeit np.sum(massive_arary)

4.64 ms ± 82.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
24.7 µs ± 208 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [88]:
np.mean(massive_arary)

0.4990429926932307

In [89]:
np.std(massive_arary)

0.28878784254354184

In [90]:
np.var(massive_arary)

0.08339841800095352

## DOT PRODUCT 

In [92]:
np.random.seed(0)

In [93]:
sales_amount = np.random.randint(20,size =(5,3))

In [115]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [95]:
import pandas as pd

In [101]:
weekly_sales = pd.DataFrame(sales_amount,index=["Mon","Tues","Wed","Thurs","Fri"],
                           columns=["Almond Butter","Peanut Butter","Cashew Butter"])

In [102]:
weekly_sales


Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

## Create prices 

In [107]:
prices = np.array([10,8,12])
prices.shape

(3,)

## Create butter prices dataframe

In [114]:
butter_prices =  pd.DataFrame(prices.reshape(1,3)
                              ,index=["Price"],
                             columns=["Almond Butter","Peanut Butter","Cashew Butter"])
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [118]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [2]:
rand_arr = np.random.randint(10,size = (3,5))

In [3]:
rand_arr


array([[0, 3, 9, 2, 3],
       [1, 5, 9, 4, 2],
       [2, 8, 8, 5, 7]])

In [5]:
rand_arr.shape


(3, 5)

In [6]:
rand_arr.sort

<function ndarray.sort>

In [7]:
np.sort(rand_arr)

array([[0, 2, 3, 3, 9],
       [1, 2, 4, 5, 9],
       [2, 5, 7, 8, 8]])

# Image Sections

<img src="numpy-images/panda.png"/>

In [30]:
from matplotlib.image import imread

In [32]:
panda = imread("numpy-images/panda.png")

In [35]:
panda.shape,panda.ndim,panda.size

((2330, 3500, 3), 3, 24465000)

In [37]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src = "numpy-images/car-photo.png"/>

In [39]:
car = imread("numpy-images/car-photo.png")

In [44]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src = "numpy-images/dog-photo.png"/>

In [45]:
dog = imread("numpy-images/dog-photo.png")

In [46]:
type(dog)

numpy.ndarray